/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedTeacherRouteImport } from './routes/_authenticated/teacher'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedStoryChildIdRouteImport } from './routes/_authenticated/story.$childId'
import { Route as AuthenticatedPetChildIdRouteImport } from './routes/_authenticated/pet.$childId'
import { Route as AuthenticatedLearnChildIdRouteImport } from './routes/_authenticated/learn.$childId'
import { Route as AuthenticatedGamesChildIdRouteImport } from './routes/_authenticated/games.$childId'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTeacherRoute = AuthenticatedTeacherRouteImport.update({
  id: '/teacher',
  path: '/teacher',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStoryChildIdRoute =
  AuthenticatedStoryChildIdRouteImport.update({
    id: '/story/$childId',
    path: '/story/$childId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPetChildIdRoute = AuthenticatedPetChildIdRouteImport.update({
  id: '/pet/$childId',
  path: '/pet/$childId',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLearnChildIdRoute =
  AuthenticatedLearnChildIdRouteImport.update({
    id: '/learn/$childId',
    path: '/learn/$childId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGamesChildIdRoute =
  AuthenticatedGamesChildIdRouteImport.update({
    id: '/games/$childId',
    path: '/games/$childId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/teacher': typeof AuthenticatedTeacherRoute
  '/games/$childId': typeof AuthenticatedGamesChildIdRoute
  '/learn/$childId': typeof AuthenticatedLearnChildIdRoute
  '/pet/$childId': typeof AuthenticatedPetChildIdRoute
  '/story/$childId': typeof AuthenticatedStoryChildIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/teacher': typeof AuthenticatedTeacherRoute
  '/games/$childId': typeof AuthenticatedGamesChildIdRoute
  '/learn/$childId': typeof AuthenticatedLearnChildIdRoute
  '/pet/$childId': typeof AuthenticatedPetChildIdRoute
  '/story/$childId': typeof AuthenticatedStoryChildIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/teacher': typeof AuthenticatedTeacherRoute
  '/_authenticated/games/$childId': typeof AuthenticatedGamesChildIdRoute
  '/_authenticated/learn/$childId': typeof AuthenticatedLearnChildIdRoute
  '/_authenticated/pet/$childId': typeof AuthenticatedPetChildIdRoute
  '/_authenticated/story/$childId': typeof AuthenticatedStoryChildIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/teacher'
    | '/games/$childId'
    | '/learn/$childId'
    | '/pet/$childId'
    | '/story/$childId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/teacher'
    | '/games/$childId'
    | '/learn/$childId'
    | '/pet/$childId'
    | '/story/$childId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/dashboard'
    | '/_authenticated/teacher'
    | '/_authenticated/games/$childId'
    | '/_authenticated/learn/$childId'
    | '/_authenticated/pet/$childId'
    | '/_authenticated/story/$childId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/teacher': {
      id: '/_authenticated/teacher'
      path: '/teacher'
      fullPath: '/teacher'
      preLoaderRoute: typeof AuthenticatedTeacherRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/story/$childId': {
      id: '/_authenticated/story/$childId'
      path: '/story/$childId'
      fullPath: '/story/$childId'
      preLoaderRoute: typeof AuthenticatedStoryChildIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pet/$childId': {
      id: '/_authenticated/pet/$childId'
      path: '/pet/$childId'
      fullPath: '/pet/$childId'
      preLoaderRoute: typeof AuthenticatedPetChildIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/learn/$childId': {
      id: '/_authenticated/learn/$childId'
      path: '/learn/$childId'
      fullPath: '/learn/$childId'
      preLoaderRoute: typeof AuthenticatedLearnChildIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/games/$childId': {
      id: '/_authenticated/games/$childId'
      path: '/games/$childId'
      fullPath: '/games/$childId'
      preLoaderRoute: typeof AuthenticatedGamesChildIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedTeacherRoute: typeof AuthenticatedTeacherRoute
  AuthenticatedGamesChildIdRoute: typeof AuthenticatedGamesChildIdRoute
  AuthenticatedLearnChildIdRoute: typeof AuthenticatedLearnChildIdRoute
  AuthenticatedPetChildIdRoute: typeof AuthenticatedPetChildIdRoute
  AuthenticatedStoryChildIdRoute: typeof AuthenticatedStoryChildIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedTeacherRoute: AuthenticatedTeacherRoute,
  AuthenticatedGamesChildIdRoute: AuthenticatedGamesChildIdRoute,
  AuthenticatedLearnChildIdRoute: AuthenticatedLearnChildIdRoute,
  AuthenticatedPetChildIdRoute: AuthenticatedPetChildIdRoute,
  AuthenticatedStoryChildIdRoute: AuthenticatedStoryChildIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
